insert into heroku_de779d0e3559015.portfolio (id, title, details, pic_one, pic_two, pic_three, pic_four, pic_five, preview, date)
values  (1, 'تطبيق الواح للقرأن الكريم', '"ألواح" هو تطبيق لتعليم قراءة القرآن الكريم للأطفال والكبار - الفكرة مستوحاة من نظام لوح القرآن المستخدم في دوائر الكتاب في الماضي. النسخة الأولى من البرنامج تحتوي على: الفاتحة + آية الكرسي + جزء عم كامل.', 'Alwah/1.jpg', 'Alwah/2.jpg', 'Alwah/3.jpg', 'Alwah/4.jpg', '', 'https://mega.nz/file/oMY0TDRJ#cnJTdSFzSh4ed8VJ5bRletsLR7yNcdtKQK-Jw6Fn5N4', '09-09-2021'),
        (2, 'تطبيق With Pencil للتعلم الالكتروني', 'هي منصة الكترونية للتعلم عن بعد عن طريق نشر الدورات التدريبية مع الاختبارات والمستويات ولكل مستوي اختبار خاص به واجتيازه وشهادة في نهاية كل مستوي تدل علي اتمامه', 'WithPencil/1.jpg', 'WithPencil/2.jpg', 'WithPencil/3.jpg', 'WithPencil/4.jpg', '', null, '25-04-2021'),
        (3, 'موقع شركة كوداكس', 'شركة كوداكس هي شركة مخصصة في الـ Graphic Design والتسويق وبرمجة تطبيقات الموبايل والانظمة', 'Codux/1.jpg', 'Codux/2.jpg', 'Codux/3.jpg', null, null, 'https://codux.me', '08-11-2020'),
        (4, 'موقع اخباري بالعربي', 'موقع اخباري بالعربي هو جريدة الكترونية لنشر الاخبار المصرية علي المنصة والبودكاست', 'Ekhbary Belaraby/1.jpg', 'Ekhbary Belaraby/2.jpg', 'Ekhbary Belaraby/3.jpg', null, null, null, '21-09-2020'),
        (5, 'موقع اكاديمية فاير اكاديمي', 'موقع تعريفي عن اكاديمية "فاير اكاديمي" والدورات التدريبية التي تقدمها الاكاديمية والمحاضرين فيها', 'Fire Academy/1.jpg', 'Fire Academy/2.jpg', 'Fire Academy/3.jpg', null, null, 'https://fire-academy.tech', '25-09-2020'),
        (6, 'موقع غنيلي لسماع الموسيقي', 'موقع غنيلي لسماع الموسيقي والاشتراك في الحزم المتوفرة وتحميل الموسيقي', 'Ghannely Web/1.jpg', 'Ghannely Web/2.jpg', 'Ghannely Web/3.jpg', null, null, 'https://ghannely.com', '08-06-2021'),
        (7, 'اكاديمية Sary Academy', 'سيستم اوفلاين بدون انترنت Real-time ، مكون من جزئين جزء لتسجيل حضور وانصراف الموظفين عن طريق جهاز البصمة وتسجيلها في النظام المخصص لذلك ونظام دخول قاعة الـ Kids area واشتراكات وحساب المدة عن طريق جهاز يمرر الطفل الكارت التي شحن عليه رصيد للدخول علي غرفة الالعاب ويخرج بعد مدة معينة ويتم سحب من الكارت بتاعه عدد الساعات تلقائياً', 'Sary Academy IOT/1.png', 'Sary Academy IOT/2.png', 'Sary Academy IOT/3.png', 'Sary Academy IOT/4.png', 'Sary Academy IOT/5.png', null, '01-05-2021'),
        (8, 'موقع جريدة NewsArea الالكترونية', 'موقع اخباري في الشرق الاوسط لنشر جميع الاخبار المتعلقة بريادة الاعمال والاقتصاد بكل ما هو متعلق بكل الدول في الشرق الاوسط ونشر البودكاست والمجلات الالكترونية الخاصة به', 'NewsArea/1.jpg', 'NewsArea/2.jpg', 'NewsArea/3.jpg', 'NewsArea/4.jpg', 'NewsArea/5.jpg', 'https://newsarea-me.com', '14-01-2021'),
        (9, 'نظام ERP خاص بـ Sary Academy', 'نظام تخطيط موارد مؤسسة Sary Academy به تسجيل لجميع الطلاب في المدرسة والمصروفات ونظام اختبارات وتصحيح ألي وكل الايرادات والمصروفات المتعلقة بأكاديمية ساري اكاديمي مع نظام اضافة مستخدمين بصلاحيات', 'Sary Academy ERP/1.png', 'Sary Academy ERP/2.png', 'Sary Academy ERP/3.png', 'Sary Academy ERP/4.png', 'Sary Academy ERP/5.png', 'http://saryacademy.com/dashboard/login', '08-04-2021'),
        (10, 'متجر الكتروني The Tailorist', 'متجر الكتروني خاص بالازياء والموضة من رجال واناث واطفال ولبس زفاف تأجير وبيع مع نظام تتبع شحنات ودفع الكتروني', 'The Tailorist/1.jpg', 'The Tailorist/2.jpg', 'The Tailorist/3.jpg', 'The Tailorist/4.jpg', 'The Tailorist/5.jpg', 'https://the-tailorist.com', '01-01-2021'),
        (11, 'نظام ERP خاص بقناة ينابيع العلم', 'نظام تخطيط موارد مؤسسة اكاديمية قناة ينابيع العلم به تسجيل لجميع الطلاب في الاكاديمية والمصروفات ونظام اختبارات وتصحيح ألي وكل الايرادات والمصروفات المتعلقة بأكاديمية ينابيع العلم مع نظام اضافة مستخدمين بصلاحيات

', 'Yanabee ERP/1.jpg', 'Yanabee ERP/2.jpg', 'Yanabee ERP/3.jpg', 'Yanabee ERP/4.jpg', null, 'https://www.yanabee-academy.com/dashboard/login', '05-05-2021'),
        (12, 'تطبيق عالم رياض الاطفال', 'تطبيق عالم رياض الاطفال يتم فيه نشر المناهج التعليمية للاطفال والمعلمون في الوطن العربي', 'Kindergarten/1.jpg', 'Kindergarten/2.jpg', 'Kindergarten/3.jpg', 'Kindergarten/4.jpg', 'Kindergarten/5.jpg', 'https://play.google.com/store/apps/details?id=com.itgo.kindergartenworld', '15-08-2021'),
        (13, 'موقع أولي جامعة', 'موقع أولي جامعة Ola-gam3a.com هو موقع مخصص لمرحلة ما قبل الثانوية لمساعدة الطلاب في الحصول علي الكليات المتاحة وفقاً لمجموع الثانوية الخاص بها ومعرفة مصاريف الجامعه واقسامها والبدائل لها وتفاصيل كل قسم من اقسامها', 'Ola-gam3a/1.jpeg', 'Ola-gam3a/2.png', null, null, null, 'https://ola-gam3a.com/', '16-06-2021'),
        (14, 'موقع موفيانا لمشاهدة الافلام', 'موقع موفيانا لمشاهدة الافلام والرسوم المتحركة والمجلات الكرتونية والتحميل بواسطة سيرفرات تورنت او المشاهدة مباشرة', 'Moviana/1.jpg', 'Moviana/2.jpg', null, null, null, 'https://moviana.netlify.app/', '07-04-2021'),
        (15, 'تطبيق غنيلي لسماع الموسيقي', 'تطبيق غنيلي لسماع الموسيقي والاشتراك في الحزم المتوفرة وتحميل الموسيقي', 'Ghannely App/1.jpg', 'Ghannely App/2.jpg', 'Ghannely App/3.jpg', 'Ghannely App/4.jpg', 'Ghannely App/5.jpg', null, '07-03-2021'),
        (16, 'تطبيق ويب لاختبارات الثانوية', 'تطبيق ويب يظهر به الاختبارات ونظام تصحيح ألي واشعارات Real-time في الحسابات', 'Thanawya/1.jpg', 'Thanawya/2.jpg', null, null, null, 'https://thanawya.netlify.app/', '07-04-2021'),
        (17, 'موقع وردة لجمع التبرعات', 'موقع وردة هو موقع تواصل اجتماعي لجمع التبرعات والتواصل مع الاعضاء به نظام شات ونظام توثيق للحسابات وتحويل اموال', 'Warda/1.jpg', 'Warda/2.jpg', 'Warda/3.png', 'Warda/4.png', null, 'https://wardaweb.netlify.app/', '30-04-2021'),
        (18, 'موقع ويب لشركة شحنة للتوصيل', 'سيستم شركة شحنة لتوصيل الطلبيات مرتبط بتطبيق خاص بالمندوبين وتطبيق للعملاء به جميع المتاجر ويمكن من خلال لوحة التحكم هذه اضافة منتجات للمتجر وشحنات ومندوبين والتحكم الكامل في المتجر الخاص بالتاجر', 'Shuhna Web/1.png', 'Shuhna Web/2.png', 'Shuhna Web/3.png', 'Shuhna Web/4.png', 'Shuhna Web/5.png', 'https://shuhna.co', '06-08-2021');